name = "argomedo455"
main = "worker.js"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "argomedo455-db"
database_id = "bf33a21d-5fb9-48be-b877-b4e914beafc5"
[[durable_objects.bindings]]
name = "REALTIME_HUB"
class_name = "RealtimeHub"

[[migrations]]
tag = "v1"
new_classes = ["RealtimeHub"]
